# Generated by Django 2.0.6 on 2018-07-25 00:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reachapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideposting',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='rider',
        ),
        migrations.AddField(
            model_name='profile',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rideposting',
            name='seats_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rideposting',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RidePosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riderrequests', to=settings.AUTH_USER_MODEL, verbose_name='The rider taking the ride'),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='confirmed_riders',
            field=models.ManyToManyField(blank=True, related_name='Rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='date',
            field=models.DateField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='dest',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rides_from', to='reachapi.Place'),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='potential_riders',
            field=models.ManyToManyField(blank=True, related_name='Ride_Offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='start',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rides_to', to='reachapi.Place'),
        ),
        migrations.AlterField(
            model_name='rideposting',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, editable=False, size=100),
        ),
    ]
